version: '3.1'
services:
  mysql-standalone:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: finances
      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - "3306:3306"

  springboot-docker-container:
    image: springboot-docker-container
    container_name: app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/finances?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-standalone